In [1]:
import urllib.request, urllib.parse, urllib.error
from bs4 import BeautifulSoup
import ssl
import json
import re
import sys
from splinter import Browser
import os
import csv
import threading
import requests
import pymongo
import pandas as pd
import string

In [2]:
# Initialize PyMongo to work with MongoDBs
conn = 'mongodb://localhost:27017'
client = pymongo.MongoClient(conn)

In [3]:
db = client.Hotels_db
collection = db.items

In [10]:
#executable_path = {'executable_path': 'chromedriver.exe'}
#browser = Browser('chrome', **executable_path, headless=False)

In [11]:
#url="https://ca.hotels.com/search.do?resolved-location=GEO_LOCATION%3AToronto,%20ON%20M2N%200H1,%20Canada%7C43.75801086425781%7C-79.40361022949219%3AGEOCODE%3AUNKNOWN&q-destination=Toronto,%20ON%20M2N%200H1,%20Canada&q-check-in=2019-04-16&q-check-out=2019-04-17&q-rooms=1&q-room-0-adults=2&q-room-0-children=0&sort-order=DISTANCE_FROM_LANDMARK"
##url="https://ca.hotels.com/search.do?resolved-location=GEO_LOCATION%3AToronto,%20ON%20M2N%200H1,%20Canada%7C43.75801086425781%7C-79.40361022949219%3AGEOCODE%3AUNKNOWN&q-destination=Toronto,%20ON%20M2N%200H1,%20Canada&q-check-in=2019-04-16&q-check-out=2019-04-17&q-rooms=1&q-room-0-adults=2&q-room-0-children=0&sort-order=DISTANCE_FROM_LANDMARK"
#browser.visit(url)
#html = browser.html
#soup = BeautifulSoup(html, 'html.parser')

In [4]:
url_list= [line.strip() for line in open("Book2.txt", 'r')]
#url_list= ["https://ca.hotels.com/search.do?resolved-location=GEO_LOCATION%3AToronto,%20ON%20M5T%202V4,%20Canada%7C43.650338%7C-79.402688%3AGEOCODE%3AUNKNOWN&q-destination=Toronto,%20ON%20M5T%202V4,%20Canada&q-check-in=2019-04-19&q-check-out=2019-04-20&q-rooms=1&q-room-0-adults=2&q-room-0-children=0&sort-order=DISTANCE_FROM_LANDMARK","https://ca.hotels.com/search.do?resolved-location=GEO_LOCATION%3AScarborough,%20ON%20M1H%202Z1,%20Canada%7C43.7827949%7C-79.2384188%3AGEOCODE%3AUNKNOWN&q-destination=Scarborough,%20ON%20M1H%202Z1,%20Canada&q-check-in=2019-04-19&q-check-out=2019-04-20&q-rooms=1&q-room-0-adults=2&q-room-0-children=0&sort-order=DISTANCE_FROM_LANDMARK","https://ca.hotels.com/search.do?resolved-location=GEO_LOCATION%3AEtobicoke,%20ON%20M9C%205K5,%20Canada%7C43.6511117%7C-79.6017779%3AGEOCODE%3AUNKNOWN&q-destination=Etobicoke,%20ON%20M9C%205K5,%20Canada&q-check-in=2019-04-19&q-check-out=2019-04-20&q-rooms=1&q-room-0-adults=2&q-room-0-children=0&sort-order=DISTANCE_FROM_LANDMARK","https://ca.hotels.com/search.do?resolved-location=GEO_LOCATION%3AEtobicoke,%20ON%20M9W%205E7,%20Canada%7C43.6788872%7C-79.5908946%3AGEOCODE%3AUNKNOWN&q-destination=Etobicoke,%20ON%20M9W%205E7,%20Canada&q-check-in=2019-04-19&q-check-out=2019-04-20&q-rooms=1&q-room-0-adults=2&q-room-0-children=0&sort-order=DISTANCE_FROM_LANDMARK","https://ca.hotels.com/search.do?resolved-location=GEO_LOCATION%3AToronto,%20ON%20M4P%202L2,%20Canada%7C43.7090152%7C-79.3906374%3AGEOCODE%3AUNKNOWN&q-destination=Toronto,%20ON%20M4P%202L2,%20Canada&q-check-in=2019-04-19&q-check-out=2019-04-20&q-rooms=1&q-room-0-adults=2&q-room-0-children=0&sort-order=DISTANCE_FROM_LANDMARK","https://ca.hotels.com/search.do?resolved-location=GEO_LOCATION%3AToronto,%20ON%20M5V%201J6,%20Canada%7C43.6458413%7C-79.3918689%3AGEOCODE%3AUNKNOWN&q-destination=Toronto,%20ON%20M5V%201J6,%20Canada&q-check-in=2019-04-19&q-check-out=2019-04-20&q-rooms=1&q-room-0-adults=2&q-room-0-children=0&sort-order=DISTANCE_FROM_LANDMARK","https://ca.hotels.com/search.do?resolved-location=GEO_LOCATION%3AToronto,%20ON%20M5B%202G8,%20Canada%7C43.655992%7C-79.3783212%3AGEOCODE%3AUNKNOWN&q-destination=Toronto,%20ON%20M5B%202G8,%20Canada&q-check-in=2019-04-19&q-check-out=2019-04-20&q-rooms=1&q-room-0-adults=2&q-room-0-children=0&sort-order=DISTANCE_FROM_LANDMARK","https://ca.hotels.com/search.do?resolved-location=GEO_LOCATION%3AToronto,%20ON%20M5C%201N2,%20Canada%7C43.6516588%7C-79.3779693%3AGEOCODE%3AUNKNOWN&q-destination=Toronto,%20ON%20M5C%201N2,%20Canada&q-check-in=2019-04-19&q-check-out=2019-04-20&q-rooms=1&q-room-0-adults=2&q-room-0-children=0&sort-order=DISTANCE_FROM_LANDMARK","https://ca.hotels.com/search.do?resolved-location=GEO_LOCATION%3AToronto,%20ON%20M5G%201Z4,%20Canada%7C43.6586116%7C-79.3833359%3AGEOCODE%3AUNKNOWN&q-destination=Toronto,%20ON%20M5G%201Z4,%20Canada&q-check-in=2019-04-19&q-check-out=2019-04-20&q-rooms=1&q-room-0-adults=2&q-room-0-children=0&sort-order=DISTANCE_FROM_LANDMARK","https://ca.hotels.com/search.do?resolved-location=GEO_LOCATION%3AEtobicoke,%20ON%20M9W%206K5,%20Canada%7C43.7208308%7C-79.5989694%3AGEOCODE%3AUNKNOWN&q-destination=Etobicoke,%20ON%20M9W%206K5,%20Canada&q-check-in=2019-04-19&q-check-out=2019-04-20&q-rooms=1&q-room-0-adults=2&q-room-0-children=0&sort-order=DISTANCE_FROM_LANDMARK"]
post = {}

source_loaded = 'Hotels.com'
for link in url_list:
    executable_path = {'executable_path': '/usr/local/bin/chromedriver'}
    browser = Browser('chrome', **executable_path, headless=False)
    browser.visit(link)
    html = browser.html
    soup = BeautifulSoup(html, 'html.parser')
    results = soup.find_all('section', class_="hotel-wrap")
        
    for result in results:
    # Error handling
        try:
            # Identify and return title of listing
            address = result.find('address', class_="contact").text

            # # Identify and return price of listing
            price = result.find('a', class_="price-link").text


            # Print results only if postal code and price are available
            if (address,price):
                print('-------------')
                address_split = address.split(sep=',')
                if len(address_split) > 6:
                    postal_code = address_split[4]
                    print(f'Postal code: {postal_code}')
                
                else :
                    postal_code = address_split[3]
                    print(f'Postal code: {postal_code}')

                prices = price.split(sep='CAD')
                
                if len(prices) > 2:
                    new_prices = prices[1]
                    print(f'new price is: {new_prices}')

                else :
                    new_prices = prices[0]
                    print(f'new price is: {new_prices}')
                # Dictionary to be inserted as a MongoDB document
                post = {
                    'postal_code': postal_code,
                    'price': new_prices,
                    'source_loaded': source_loaded,
                    #'FSA':FSA
                    }
                collection.insert_one(post)
                # Convert to DataFrame
                #hotel_pd = pd.DataFrame(post)
                #hotel_pd = hotel_pd[["postal_code", "price","source_loaded"]]
                
                #hotel_pd.to_csv("hotel_pd_data.csv", encoding="utf-8", index=False)


        except AttributeError as e:
            print(e)

-------------
Postal code:  M5T2V4
new price is: $119
-------------
Postal code:  M5T2S3
new price is: $139
-------------
Postal code:  M5T 1H5
new price is: $59
-------------
Postal code:  M6J 2G4
new price is: $134
-------------
Postal code:  M5T1E8
new price is: $69
-------------
Postal code:  M1H2Z1
new price is: $144
-------------
Postal code:  M1H2Z1
new price is: $140
-------------
Postal code:  M1B3C6
new price is: $118
-------------
Postal code:  M1T-3G2
new price is: $154
-------------
Postal code:  Canada
new price is: $58
-------------
Postal code:  M9C5K5
new price is: $169
-------------
Postal code:  M9C 5K5
new price is: $149
-------------
Postal code:  M9C 5K5
new price is: $124
-------------
Postal code:  L4W4X2
new price is: $139
-------------
Postal code:  L4W5R2
new price is: $139
-------------
Postal code:  M9W 5E7
new price is: $146
-------------
Postal code:  M9W5E8
new price is: $130
-------------
Postal code:  M9W 5E8
new price is: $199
-------------
Postal code:  M9W1J5
new price is: $129
-------------
Postal code:  M9W1J5
new price is: $139
-------------
Postal code:  M4P2L2
new price is: $119
-------------
Postal code:  M5R 2G3
new price is: $134
-------------
Postal code:  M4W 0A4
new price is: $599
-------------
Postal code:  M5R1C2
new price is: $699
-------------
Postal code:  M4W1A7
new price is: $169
-------------
Postal code:  M5V 2G3
new price is: $309
-------------
Postal code:  M5V 1J9
new price is: $179
-------------
Postal code:  M5V1H3
new price is: $306
-------------
Postal code:  M5V3T4
new price is: $260
-------------
Postal code:  M5V3P9
new price is: $199
-------------
Postal code:  M5B2G8
new price is: $149
-------------
Postal code:  M5B 1V8
new price is: $237
-------------
Postal code:  M5B2C1
new price is: $221
-------------
Postal code:  M5G 2L2
new price is: $209
-------------
Postal code:  M5C 1S2
new price is: $299
-------------
Postal code:  M5C1N2
new price is: $199
-------------
Postal code:  M5C1E9
new price is: $212
-------------
Postal code:  M5H1A1
new price is: $152
-------------
Postal code:  M5H 4G3
new price is: $509
-------------
Postal code:  M5C 1S2
new price is: $299
-------------
Postal code:  M5G1Z4
new price is: $149
-------------
Postal code:  M5B1G3
new price is: $229
-------------
Postal code:  M5B 1H2
new price is: $129
-------------
Postal code:  M5B2E9
new price is: $170
-------------
Postal code:  M4Y1X7
new price is: $169
-------------
Postal code:  M9W 6K5
new price is: $145
-------------
Postal code:  M9W7A4
new price is: $120
-------------
Postal code:  M9W1H3
new price is: $135
-------------
Postal code:  M9W7K7
new price is: $119
-------------
Postal code:  M9W 7K7
new price is: $159
-------------
Postal code:  M4Y 1S1
new price is: $219
-------------
Postal code:  M4W1A7
new price is: $169
-------------
Postal code:  M4Y2G2
new price is: $149
-------------
Postal code:  M4Y1L5
new price is: $119
-------------
Postal code:  M4Y1G7
new price is: $278
-------------
Postal code:  M5B2C2
new price is: $129
-------------
Postal code:  M5B2C5
new price is: $139
-------------
Postal code:  M5A2N9
new price is: $115
-------------
Postal code:  M5B 1H2
new price is: $129
-------------
Postal code:  M5B2C1
new price is: $221
-------------
Postal code:  M4Y1X7
new price is: $169
-------------
Postal code:  M5B2E9
new price is: $170
-------------
Postal code:  M5B 1H2
new price is: $129
-------------
Postal code:  M4Y1G7
new price is: $278
-------------
Postal code:  M5B1G3
new price is: $229
-------------
Postal code:  M9W5E8
new price is: $130
-------------
Postal code:  M9W 5E8
new price is: $199
-------------
Postal code:  M9W1J5
new price is: $129
-------------
Postal code:  M9W1J8
new price is: $129
-------------
Postal code:  M9W5G1
new price is: $159
-------------
Postal code:  M4J1L9
new price is: $95
-------------
Postal code:  M4M 1Y3
new price is: $49
-------------
Postal code:  M4M2G1
new price is: $234
'NoneType' object has no attribute 'text'
-------------
Postal code:  M5A2A5
new price is: $149
-------------
Postal code:  M5A 2T3
new price is: $109
-------------
Postal code:  M1T-3G2
new price is: $154
-------------
Postal code:  Canada
new price is: $58
-------------
Postal code:  M1R 2T6
new price is: $99
-------------
Postal code:  M1H2Z1
new price is: $144
-------------
Postal code:  M1H2Z1
new price is: $140
-------------
Postal code:  M5J0A9
new price is: $399
-------------
Postal code:  M5J 0A6
new price is: $139
-------------
Postal code:  Canada
new price is: $215
-------------
Postal code:  M5J3A6
new price is: $209
-------------
Postal code:  M5J 0A9
new price is: $440
-------------
Postal code:  M5G1R3
new price is: $169
-------------
Postal code:  M5G 2L2
new price is: $209
-------------
Postal code:  M5H2M9
new price is: $169
-------------
Postal code:  M5H2L2
new price is: $169
'NoneType' object has no attribute 'text'
-------------
Postal code:  M5H0B1
new price is: $179
-------------
Postal code:  M6J 1J3
new price is: $299
-------------
Postal code:  M6J 1J6
new price is: $229
-------------
Postal code:  M6K 3C3
new price is: $301
-------------
Postal code:  M6R 1A5
new price is: $52
-------------
Postal code:  M6J 2J1
new price is: $929

WebDriverException: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"Cannot navigate to invalid URL"}
  (Session info: chrome=73.0.3683.103)
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Mac OS X 10.14.4 x86_64)

In [5]:
#db.items.remove()
listings = db.items.find()
listings

In [6]:
import json

In [7]:
# Display items in MongoDB collection
df =  pd.DataFrame(list(listings))
df.head()

                        _id postal_code  price source_loaded
0  5cb7cac567e0daed3a7ef4a9      M5T2V4  $119     Hotels.com
1  5cb7cac567e0daed3a7ef4aa      M5T2S3  $139     Hotels.com
2  5cb7cac567e0daed3a7ef4ab     M5T 1H5   $59     Hotels.com
3  5cb7cac567e0daed3a7ef4ac     M6J 2G4  $134     Hotels.com
4  5cb7cac567e0daed3a7ef4ad      M5T1E8   $69     Hotels.com

In [8]:
df.to_csv("Hotel_list_raw.csv", index=True)

In [9]:
new_customer_location_df = df[["postal_code", "price", "source_loaded"]].copy()
new_customer_location_df.head()

  postal_code  price source_loaded
0      M5T2V4  $119     Hotels.com
1      M5T2S3  $139     Hotels.com
2     M5T 1H5   $59     Hotels.com
3     M6J 2G4  $134     Hotels.com
4      M5T1E8   $69     Hotels.com

In [10]:
new_customer_location_df['FSA'] = new_customer_location_df['postal_code'].astype(str).str[:4]
new_customer_location_df.head()

  postal_code  price source_loaded   FSA
0      M5T2V4  $119     Hotels.com   M5T
1      M5T2S3  $139     Hotels.com   M5T
2     M5T 1H5   $59     Hotels.com   M5T
3     M6J 2G4  $134     Hotels.com   M6J
4      M5T1E8   $69     Hotels.com   M5T

In [11]:
new_customer_location_df["price"] = new_customer_location_df["price"].apply(lambda x : x.replace('$',''))

In [12]:
new_customer_location_df["price"] = new_customer_location_df["price"].astype(float)

In [13]:
new_customer_location_df.drop_duplicates("postal_code", inplace=True)
new_customer_location_df.set_index("FSA", inplace=True)

In [14]:
new_customer_location_df.head()

     postal_code  price source_loaded
FSA
 M5T      M5T2V4  119.0    Hotels.com
 M5T      M5T2S3  139.0    Hotels.com
 M5T     M5T 1H5   59.0    Hotels.com
 M6J     M6J 2G4  134.0    Hotels.com
 M5T      M5T1E8   69.0    Hotels.com

In [15]:
new_customer_location_df.head()

     postal_code  price source_loaded
FSA
 M5T      M5T2V4  119.0    Hotels.com
 M5T      M5T2S3  139.0    Hotels.com
 M5T     M5T 1H5   59.0    Hotels.com
 M6J     M6J 2G4  134.0    Hotels.com
 M5T      M5T1E8   69.0    Hotels.com

In [16]:
new_customer_location_df.to_csv("Hotel_list.csv", index=True)